#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug  1 19:33:44 2018

@author: kpit
"""


# import modules
import itertools, random

# make a deck of cards
deck = list(itertools.product(range(1,14),['Spade','Heart','Diamond','Club']))
print (deck)
cards_player1=[]
cards_player2=[]
random.shuffle(deck)

# draw five cards
print("player1 got:")
for i in range(3):
   cards_player1.append(i)
   print(deck[i][0], "of", deck[i][1])
print("\n")   
print("\n")
print("\n")

print("player2 got:")
for i in range(3):
   cards_player2.append(i)
   print(deck[i][0], "of", deck[i][1])
print("\n")   
print("\n")
print("\n")

print("cards on board:")
for i in range(2):
    cards_player1.append(i)
    cards_player2.append(i)
    print(deck[i][0], "of", deck[i][1])
    
    
